"""Regression tests for MCP tool nested schema preservation.

Tests that MCP tools with nested object parameters preserve their full
JSON Schema structure (properties, required, enums, arrays) in the
LLM-facing schema generated by ``to_openai_tool()`` and
``to_responses_tool()``.

Regression coverage for:
    https://github.com/yqwd-dimleap/suricate-sdk/issues/3955
"""

import json
from typing import Any, ClassVar
from unittest.mock import MagicMock

import mcp.types

from openhands.sdk.mcp.definition import MCPToolAction
from openhands.sdk.mcp.tool import MCPToolDefinition, MCPToolExecutor


class DummyExecutor(MCPToolExecutor):
    """Minimal executor that satisfies MCPToolDefinition.create()."""

    def __init__(self):
        self.tool_name = "dummy"
        self.client = MagicMock()
        self.timeout = 300


def _make_tool(
    name: str, input_schema: dict[str, Any], description: str = "test"
) -> MCPToolDefinition:
    """Build an MCPToolDefinition from a raw inputSchema dict."""
    mcp_tool = mcp.types.Tool(
        name=name,
        description=description,
        inputSchema=input_schema,
    )
    return MCPToolDefinition(
        description=description,
        action_type=MCPToolAction,
        observation_type=None,
        executor=DummyExecutor(),
        mcp_tool=mcp_tool,
    )


def _get_params(tool: MCPToolDefinition, **kwargs: Any) -> dict[str, Any]:
    """Extract the ``parameters`` dict from the generated OpenAI tool."""
    openai_tool = tool.to_openai_tool(**kwargs)
    return dict(openai_tool)["function"]["parameters"]  # type: ignore[index]


# ---------------------------------------------------------------------------
# The exact reproduction from issue #3955
# ---------------------------------------------------------------------------


class TestNestedObjectPreservation:
    """MCP tools with nested object parameters must preserve their full
    JSON Schema structure in the LLM-facing schema.
    """

    INPUT_SCHEMA: ClassVar[dict[str, Any]] = {
        "type": "object",
        "properties": {
            "definition": {
                "description": "Component model ID",
                "type": "string",
            },
            "position": {
                "description": "Component position",
                "type": "object",
                "properties": {
                    "0": {"type": "number"},
                    "1": {"type": "number"},
                },
                "required": ["0", "1"],
            },
        },
        "required": ["definition", "position"],
    }

    def _get_position_field(self, add_security_risk: bool = False) -> dict[str, Any]:
        """Extract the ``position`` field from the generated schema."""
        tool = _make_tool("add_diagram_component", self.INPUT_SCHEMA)
        params = _get_params(tool, add_security_risk_prediction=add_security_risk)
        return params["properties"]["position"]

    def test_nested_properties_preserved(self) -> None:
        """Regression: position.properties must not be flattened."""
        position = self._get_position_field()
        assert "properties" in position, (
            "Nested object properties were lost in LLM-facing schema "
            f"(got {json.dumps(position)})"
        )
        assert position["properties"]["0"] == {"type": "number"}
        assert position["properties"]["1"] == {"type": "number"}

    def test_nested_required_preserved(self) -> None:
        """Regression: position.required must not be dropped."""
        position = self._get_position_field()
        assert "required" in position
        assert set(position["required"]) == {"0", "1"}

    def test_nested_description_preserved(self) -> None:
        """The description on the nested object should survive."""
        position = self._get_position_field()
        assert position.get("description") == "Component position"

    def test_with_security_risk(self) -> None:
        """Nested properties must survive when security_risk is added."""
        position = self._get_position_field(add_security_risk=True)
        assert "properties" in position
        assert set(position["required"]) == {"0", "1"}

    def test_responses_tool_preserves_nested(self) -> None:
        """to_responses_tool() must also preserve nested properties."""
        tool = _make_tool("add_diagram_component", self.INPUT_SCHEMA)
        responses_tool = tool.to_responses_tool()
        params: dict[str, Any] = responses_tool["parameters"]  # type: ignore[assignment]
        position = params["properties"]["position"]
        assert "properties" in position
        assert position["properties"]["0"] == {"type": "number"}
        assert position["properties"]["1"] == {"type": "number"}
        assert set(position["required"]) == {"0", "1"}


# ---------------------------------------------------------------------------
# Deeper nesting and mixed-type schemas
# ---------------------------------------------------------------------------


class TestDeeplyNestedSchema:
    """Schemas with multiple levels of nesting."""

    def test_three_level_nesting(self) -> None:
        """Three levels deep: tool -> config -> theme -> colors."""
        schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "config": {
                    "type": "object",
                    "description": "App configuration",
                    "properties": {
                        "theme": {
                            "type": "object",
                            "description": "Theme settings",
                            "properties": {
                                "primary": {"type": "string"},
                                "secondary": {"type": "string"},
                            },
                            "required": ["primary"],
                        }
                    },
                    "required": ["theme"],
                }
            },
            "required": ["config"],
        }
        tool = _make_tool("configure_app", schema)
        params = _get_params(tool)
        config = params["properties"]["config"]
        assert "properties" in config
        theme = config["properties"]["theme"]
        assert "properties" in theme
        assert theme["properties"]["primary"] == {"type": "string"}
        assert theme["properties"]["secondary"] == {"type": "string"}
        assert theme["required"] == ["primary"]
        assert config["required"] == ["theme"]

    def test_nested_array_of_objects(self) -> None:
        """Array items with object schemas should be preserved."""
        schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "description": "List of entries",
                    "items": {
                        "type": "object",
                        "properties": {
                            "id": {"type": "integer"},
                            "label": {"type": "string"},
                        },
                        "required": ["id"],
                    },
                }
            },
        }
        tool = _make_tool("batch_create", schema)
        params = _get_params(tool)
        items_field = params["properties"]["items"]
        assert items_field["type"] == "array"
        item_schema = items_field["items"]
        assert "properties" in item_schema
        assert item_schema["properties"]["id"] == {"type": "integer"}
        assert item_schema["required"] == ["id"]


# ---------------------------------------------------------------------------
# Suricate-injected fields
# ---------------------------------------------------------------------------


class TestInjectedFields:
    """Verify that Suricate-specific fields (security_risk, summary)
    are correctly injected alongside nested MCP properties.
    """

    SIMPLE_NESTED: ClassVar[dict[str, Any]] = {
        "type": "object",
        "properties": {
            "data": {
                "type": "object",
                "properties": {"x": {"type": "number"}},
            }
        },
    }

    def test_summary_injected(self) -> None:
        """summary must appear in the LLM schema."""
        tool = _make_tool("test_tool", self.SIMPLE_NESTED)
        params = _get_params(tool)
        assert "summary" in params["properties"]

    def test_security_risk_injected(self) -> None:
        """security_risk must appear when requested."""
        tool = _make_tool("test_tool", self.SIMPLE_NESTED)
        params = _get_params(tool, add_security_risk_prediction=True)
        assert "security_risk" in params["properties"]
        sr = params["properties"]["security_risk"]
        assert "enum" in sr
        assert "UNKNOWN" in sr["enum"]

    def test_security_risk_not_injected_for_readonly(self) -> None:
        """Read-only tools should NOT get security_risk."""
        from openhands.sdk.tool import ToolAnnotations

        mcp_tool = mcp.types.Tool(
            name="readonly_tool",
            description="read only",
            inputSchema=self.SIMPLE_NESTED,
        )
        tool = MCPToolDefinition(
            description="read only",
            action_type=MCPToolAction,
            observation_type=None,
            executor=DummyExecutor(),
            mcp_tool=mcp_tool,
            annotations=ToolAnnotations(readOnlyHint=True),
        )
        params = _get_params(tool, add_security_risk_prediction=True)
        assert "security_risk" not in params["properties"]

    def test_summary_not_injected_when_tool_declares_summary(self) -> None:
        """If the MCP tool itself declares a 'summary' parameter (e.g.,
        Jira ticket title), our meta-summary must not shadow it.
        """
        schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "summary": {
                    "type": "string",
                    "description": "Jira ticket title",
                },
                "body": {"type": "string"},
            },
            "required": ["summary"],
        }
        tool = _make_tool("create_ticket", schema)
        params = _get_params(tool)
        # The tool's own summary must be preserved, not replaced
        assert params["properties"]["summary"]["description"] == "Jira ticket title"

    def test_priority_ordering(self) -> None:
        """security_risk and summary should appear before tool params."""
        tool = _make_tool("test_tool", self.SIMPLE_NESTED)
        params = _get_params(tool, add_security_risk_prediction=True)
        keys = list(params["properties"].keys())
        # security_risk and summary should be first two
        assert keys[0] == "security_risk"
        assert keys[1] == "summary"


# ---------------------------------------------------------------------------
# Flat schemas still work
# ---------------------------------------------------------------------------


class TestFlatSchemaUnchanged:
    """Flat (non-nested) MCP schemas should still work correctly."""

    def test_flat_string_params(self) -> None:
        schema: dict[str, Any] = {
            "type": "object",
            "properties": {
                "query": {"type": "string", "description": "Search query"},
                "limit": {"type": "integer", "description": "Max results"},
            },
            "required": ["query"],
        }
        tool = _make_tool("search", schema)
        params = _get_params(tool)
        assert params["properties"]["query"] == {
            "type": "string",
            "description": "Search query",
        }
        assert params["properties"]["limit"] == {
            "type": "integer",
            "description": "Max results",
        }
        assert "query" in params["required"]

    def test_empty_properties(self) -> None:
        """Tool with no properties at all."""
        schema: dict[str, Any] = {"type": "object"}
        tool = _make_tool("no_args", schema)
        params = _get_params(tool)
        # Should still have summary injected
        assert "summary" in params["properties"]
